### ISSUE TITLE
getting output.png complete black.

### ISSUE THREAD

**Issue by 008karan** [RohanBhandari/SmartFit#1]
I ran the test but getting a complete black image. I followed the steps as mentioned.
Please help.

**Comment by RohanBhandari** [comment]
Are you using Octave 4.2 with the image package?

Can you check `try-on/results/stage1/images/` and see if the image is non-black here? This will help determine at what step the issue is at.

**Comment by 008karan** [comment]
Thanks for help. Now getting results. But the thing is when I try with different example not getting clear results. Is  there any size restriction? Quality of image also degrades in output any idea regarding that?

**Comment by RohanBhandari** [comment]
It's difficult to say what the exact issue may be without seeing the input and output image.

The image size does need to be down-sampled so that tensorflow doesn't crash due to very large input sizes. The best thing would be to crop and down-sample the image such that it is 256x192, but it works well for sizes 1-3x larger as well.

The output image quality will be degraded, as the network currently outputs a 256x192 image. That resolution loss is unavoidable. A future project is to increase the output size.

**Comment by 008karan** [comment]
Thanks for the explanation. 
I observed that it does struggle at edges and does not produce good result with all test images. Like some color of clothes on hands , weird hand fingers, change of jeans color etc. Do you think all this can be improved and can we generate HD images like the input? Any thoughts, suggestions are welcome!

**Comment by RohanBhandari** [comment]
Yes, there is still some variation in the quality of the results, which is dependent on a few factors related both to the network architecture and features of the input image. There is currently a fix for the changing jeans color, but that model is not public yet, and there are ways to improve the hands that have not yet been implemented.
All in all, there is still some interesting work left to do to continue improving the results.
